name: CI for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для data_bus
  data_bus:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Использование последней стабильной версии actions/checkout

    - name: Set up Python for data_bus
      uses: actions/setup-python@v3  # Использование последней стабильной версии actions/setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Установка зависимостей из репозитория
        pip install pytest  # Установка pytest

    - name: Run tests for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        pytest  # Запуск тестов для data_bus

    - name: Build application for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        mkdir -p ./microservices_project/data_bus/build  # Создание папки для сборки
        echo "Build step for data_bus" > ./microservices_project/data_bus/build/build_info.txt  # Пример содержания

    - name: Check build folder contents for data_bus
      run: |
        ls -la ./microservices_project/data_bus/build  # Выводим содержимое папки build для диагностики

    - name: Publish build artifacts for data_bus
      uses: actions/upload-artifact@v2  # Использование стабильной версии actions/upload-artifact v2
      with:
        name: data_bus-artifacts
        path: ./microservices_project/data_bus/build  # Путь к артефактам
