name: CI for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для data_bus
  data_bus:
    runs-on: ubuntu-latest  # Используйте актуальный runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Использование последней стабильной версии actions/checkout

    - name: Set up Python for data_bus
      uses: actions/setup-python@v3  # Использование последней стабильной версии actions/setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Установка зависимостей из репозитория
        pip install pytest  # Установка pytest

    - name: Run tests for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        pytest  # Запуск тестов для data_bus

    - name: Build application for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        echo "Build step for data_bus"  # Ваш код сборки

    - name: Check if build directory exists before creating it
      run: |
        if [ -d "./microservices_project/data_bus/build" ]; then
          echo "Build directory exists"
        else
          echo "Build directory does not exist"
        fi

    - name: Create test build artifact
      working-directory: ./microservices_project/data_bus
      run: |
        mkdir -p ./build  # Создание директории build, если она еще не существует
        echo "test artifact" > ./build/test_file.txt  # Создание тестового файла для артефакта

    - name: Verify build directory after creation
      run: |
        if [ -d "./microservices_project/data_bus/build" ]; then
          echo "Build directory created successfully"
        else
          echo "Failed to create build directory"
        fi

    - name: Upload build artifacts for data_bus
      uses: actions/upload-artifact@v2  # Использование стабильной версии actions/upload-artifact v2
      with:
        name: data_bus-artifacts
        path: ./microservices_project/data_bus/build  # Путь к артефактам

  # Аналогичные шаги для order_service и user_service...
