name: CI for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для data_bus
  data_bus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for data_bus
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies for data_bus
      working-directory: Rabota/microservices_project/data_bus/app.py
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for data_bus
      working-directory: Rabota/microservices_project/data_bus/app.py
      run: |
        pytest  # или другой тестировщик

  # Job для order_service
  order_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for order_service
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies for order_service
      working-directory: Rabota/microservices_project/order_service/app.py
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for order_service
      working-directory: Rabota/microservices_project/order_service/app.py
      run: |
        pytest  # или другой тестировщик

  # Job для user_service
  user_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for user_service
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies for user_service
      working-directory: Rabota/microservices_project/user_service/app.py
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for user_service
      working-directory: Rabota/microservices_project/user_service/app.py
      run: |
        pytest  # или другой тестировщик
