name: CI for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для data_bus
  data_bus:
    runs-on: ubuntu-latest  # Используем актуальную версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Проверенная версия для checkout

    - name: Set up Python for data_bus
      uses: actions/setup-python@v2  # Использование v2 для setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Устанавливаем pytest для тестов

    - name: Run tests for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        pytest  # Запуск тестов для data_bus

    - name: Build application for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        mkdir -p build  # Если папка build не существует, создаем ее
        echo "Build step for data_bus" > build/output.txt  # Пример записи в build

    - name: Publish build artifacts for data_bus
      uses: actions/upload-artifact@v2  # Используем стабильную версию upload-artifact v2
      with:
        name: data_bus-artifacts
        path: ./microservices_project/data_bus/build/output.txt  # Указываем путь к артефактам

  # Job для order_service
  order_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Использование v2 для checkout

    - name: Set up Python for order_service
      uses: actions/setup-python@v2  # Использование v2 для setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for order_service
      working-directory: ./microservices_project/order_service
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Устанавливаем pytest для тестов

    - name: Run tests for order_service
      working-directory: ./microservices_project/order_service
      run: |
        pytest  # Запуск тестов для order_service

    - name: Build application for order_service
      working-directory: ./microservices_project/order_service
      run: |
        mkdir -p build  # Если папка build не существует, создаем ее
        echo "Build step for order_service" > build/output.txt  # Пример записи в build

    - name: Publish build artifacts for order_service
      uses: actions/upload-artifact@v2  # Используем стабильную версию upload-artifact v2
      with:
        name: order_service-artifacts
        path: ./microservices_project/order_service/build/output.txt  # Указываем путь к артефактам для order_service

  # Job для user_service
  user_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Использование v2 для checkout

    - name: Set up Python for user_service
      uses: actions/setup-python@v2  # Использование v2 для setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for user_service
      working-directory: ./microservices_project/user_service
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Устанавливаем pytest для тестов

    - name: Run tests for user_service
      working-directory: ./microservices_project/user_service
      run: |
        pytest  # Запуск тестов для user_service

    - name: Build application for user_service
      working-directory: ./microservices_project/user_service
      run: |
        mkdir -p build  # Если папка build не существует, создаем ее
        echo "Build step for user_service" > build/output.txt  # Пример записи в build

    - name: Publish build artifacts for user_service
      uses: actions/upload-artifact@v2  # Используем стабильную версию upload-artifact v2
      with:
        name: user_service-artifacts
        path: ./microservices_project/user_service/build/output.txt  # Указываем путь к артефактам для user_service
