name: CI Pipeline for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для сборки и публикации артефактов
  build_and_publish:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Скачиваем код из репозитория

    - name: Set up Python
      uses: actions/setup-python@v3  # Устанавливаем Python
      with:
        python-version: '3.8'  # Указываем версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Обновляем pip
        pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

    - name: Build application
      run: |
        echo "Building the application..."  # Пример команды сборки
        # Например, создание архива с кодом приложения
        tar -czf app_build.tar.gz ./  # Архивируем текущий каталог

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3  # Загружаем артефакты с помощью actions/upload-artifact
      with:
        name: app-build-artifacts  # Имя артефакта
        path: app_build.tar.gz  # Путь к файлу артефакта
