name: CI for Microservices Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job для data_bus
  data_bus:
    runs-on: ubuntu-latest  # Используем актуальную версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Использование последней версии checkout

    - name: Set up Python for data_bus
      uses: actions/setup-python@v3  # Использование последней версии setup-python
      with:
        python-version: '3.8'

    - name: Install dependencies for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Установка зависимостей из репозитория
        pip install pytest  # Установка pytest

    - name: Run tests for data_bus
      working-directory: ./microservices_project/data_bus
      run: |
        pytest  # Запуск тестов для data_bus

    - name: Verify working directory and current path
      run: |
        echo "Current working directory:"
        pwd  # Печатает текущую директорию
        echo "Listing files in current directory:"
        ls -al  # Печатает список файлов в текущей директории

    - name: Create build directory
      run: |
        echo "Creating build directory..."
        mkdir -p ./microservices_project/data_bus/build  # Создаём build директорию
        echo "Creating test file inside build directory..."
        echo "test artifact" > ./microservices_project/data_bus/build/test_file.txt  # Создаём тестовый файл

    - name: Verify build directory contents
      run: |
        echo "Listing contents of build directory:"
        ls -al ./microservices_project/data_bus/build  # Проверяем содержимое build

    - name: Upload build artifacts for data_bus
      uses: actions/upload-artifact@v2  # Использование стабильной версии actions/upload-artifact v2
      with:
        name: data_bus-artifacts
        path: ./microservices_project/data_bus/build  # Путь к артефактам

  # Аналогичные шаги для order_service и user_service
